language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t devum25/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true devum25/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-reach"
  env: "Dockerreach-env"
  bucket_name: "elasticbeanstalk-ap-south-1-215137446487"
  bucket_path: "docker-reach"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY